export const enum GalleryItemTypeEnum {
  CARD_LEARN = 'CARD_LEARN',
  SENTENCE = 'SENTENCE',
  BOOK = 'BOOK',
  SEE_MORE = 'SEE_MORE',
  USER_DICTIONARY = 'USER_DICTIONARY',
  MARK_SENTENCE = 'MARK_SENTENCE',
  TEST_VOCABULARY = 'TEST_VOCABULARY'
}
