import { PartOfSpeechDto } from '@/model/partOfSpeechDto'

export const PartOfSpeechEnum: {[index: string]: PartOfSpeechDto} = {
  CC: new PartOfSpeechDto('Соединитель'),
  CD: new PartOfSpeechDto('Количественное числительное'),
  DT: new PartOfSpeechDto('Определитьель'),
  EX: new PartOfSpeechDto('Экзистенциальное "там"'),
  FW: new PartOfSpeechDto('Иностранное слово'),
  IN: new PartOfSpeechDto('Предлог/подтекст'),
  JJ: new PartOfSpeechDto('Прилагательное', 'Отвечает на вопросы "какой?", "какая?", "какое?", "какие?", "чей?" и т.д.'),
  JJR: new PartOfSpeechDto('Прилагательное сравнительное', 'Отвечает на вопросы "какой?", "какая?", "какое?", "какие?", "чей?" и т.д.'),
  JJS: new PartOfSpeechDto('Прилагательное, превосходная степень', 'Отвечает на вопросы "какой?", "какая?", "какое?", "какие?", "чей?" и т.д.'),
  LS: new PartOfSpeechDto('Номер в списке'),
  MD: new PartOfSpeechDto('Модальный глагол', 'Группа особых глаголов'),
  NN: new PartOfSpeechDto('Существительное', 'Обозначает предмет, лицо или явление и отвечающая на вопросы "кто?" или "что?"'),
  NNS: new PartOfSpeechDto('Существительное, множественное число', 'Обозначает предмет, лицо или явление и отвечающая на вопросы "кто?" или "что?"'),
  NNP: new PartOfSpeechDto('Наименование'),
  NNPS: new PartOfSpeechDto('Наименование, множественное число'),
  PDT: new PartOfSpeechDto('Предопределитель'),
  POS: new PartOfSpeechDto('Притяжательное окончание'),
  PRP: new PartOfSpeechDto('Личное местоимение', 'Местоимения, которые указывают на предмет, но не называют его'),
  PRP$: new PartOfSpeechDto('Притяжательное местоимение', 'Личное местоимение, указывающее принадлежность к участникам речи'),
  RB: new PartOfSpeechDto('Наречие', 'Обозначающая признак действия, качества. Отвечает на вопросы "где?", "когда?", "куда?", "откуда?", "почему?", "зачем?", "как?"'),
  RBR: new PartOfSpeechDto('Наречие, сравниетльная степень'),
  RBS: new PartOfSpeechDto('Наречие, превосходная степень'),
  RP: new PartOfSpeechDto('Частица', 'Вносит различные оттенки значения, эмоциональные оттенки'),
  SYM: new PartOfSpeechDto('Символ'),
  TO: new PartOfSpeechDto('TO'),
  UH: new PartOfSpeechDto('Междометие'),
  VB: new PartOfSpeechDto('Глагол, базовая форма', 'Обозначает состояние или действие и отвечает на вопросы что "делать?" что "сделать?"'),
  VBD: new PartOfSpeechDto('Глагол вторая форма'),
  VBG: new PartOfSpeechDto('Глагол, герундий'),
  VBN: new PartOfSpeechDto('Глагол третья форма'),
  VBP: new PartOfSpeechDto('Глагол'),
  VBZ: new PartOfSpeechDto('Глагол'),
  WDT: new PartOfSpeechDto('Вопрос определитель'),
  WP: new PartOfSpeechDto('Вопрос к местоимению'),
  WP$: new PartOfSpeechDto('Вопрос к притяжательному местоимению'),
  WRB: new PartOfSpeechDto('Вопрос к наречию')
}
